version: "2"

services:
  test:
    image: tuleap-run-e2e-tests-v2
    build:
      context: ./tests/e2e/DockerImage
    command: /tuleap/tests/e2e/full/run.sh
    volumes:
      - .:/tuleap
      - ${TEST_RESULT_OUTPUT}:/output
    networks:
      - tuleap
      - external-connectivity

  tuleap:
    image: enalean/tuleap-aio
    command: /usr/share/tuleap/tests/e2e/full/tuleap/setup.sh
    volumes:
      - .:/usr/share/tuleap
    networks:
      - tuleap

networks:
  tuleap:
    internal: true
  external-connectivity:
