version: "2"

services:
  tuleap:
    image: enalean/tuleap-aio
    command: /usr/share/tuleap/tests/e2e/full/tuleap/setup.sh
    volumes:
      - .:/usr/share/tuleap
    networks:
      - tuleap

networks:
  tuleap:
    internal: true
