version: "2"

services:
  tuleap:
    image: tuleap-e2e-tests
    build:
      context: ./tests/e2e/docker
      dockerfile: tuleap.dockerfile
      args:
        DOCKER_REGISTRY: ${DOCKER_REGISTRY:-docker.io}
    command: /usr/share/tuleap/tests/e2e/full/tuleap/setup.sh
    volumes:
      - .:/usr/share/tuleap
    networks:
      - tuleap
    depends_on:
      - mysql57

  mysql57:
    image: ${DOCKER_REGISTRY:-docker.io}/mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=welcome0
    volumes:
      - ./tests/etc/DBConfig/mysql-server.cnf:/etc/mysql/mysql.conf.d/mysql-server.cnf:ro,cached
    tmpfs: /tmp
    networks:
      - tuleap

networks:
  tuleap:
    internal: true
