version: "2"

services:
  reverse-proxy:
    build:
      context: tools/docker/reverse-proxy
    volumes:
      - ./tools/docker/reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro,cached
      - reverse-proxy-cert:/etc/pki/tls
    depends_on:
    - web
    - realtime

  web:
    image: enalean/tuleap-aio-dev:c6-php73-nginx
    volumes:
      - .:/usr/share/tuleap:cached
      - ../tuleap-plugins:/usr/share/tuleap-plugins:cached
      - tuleap-data:/data
      - realtime-cert:/etc/pki/ca-trust/source/anchors
    env_file:
    - .env
    depends_on:
    - ldap
    - db
    - db57
    - realtime

  realtime:
    build:
      context: tools/docker/realtime
    command: /tuleap/tools/docker/realtime/run.sh
    volumes:
      - .:/tuleap:ro,cached
      - realtime-conf:/etc/tuleap-realtime
      - realtime-cert:/published-certificate
    env_file:
      - .env

  mailhog:
    image: mailhog/mailhog

  ldap:
    image: enalean/ldap
    env_file:
    - .env
    volumes:
      - ldap-data:/data

  gerrit:
    build:
      context: tools/docker/gerrit
    env_file:
      - .env
    environment:
      - CANONICAL_WEB_URL=http://gerrit.tuleap-aio-dev.docker:8080
    volumes:
      - gerrit-data:/data
    depends_on:
      - ldap

  jenkins:
    image: jenkins/jenkins:lts
    volumes:
    - jenkins-data:/var/jenkins_home

  db:
    image: mysql:5.5
    env_file:
    - .env
    volumes:
      - db-data:/var/lib/mysql

  db57:
    image: mysql:5.7
    env_file:
      - .env
    volumes:
      - ./src/etc/tuleap-mysql57-dev.cnf:/etc/mysql/mysql.conf.d/tuleap.cnf:ro,cached
      - db57-data:/var/lib/mysql

  redis:
    image: redis:3.2
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

  prometheus:
    image: prom/prometheus:v2.3.0
    volumes:
      - .metrics_secret.key:/metrics_secret.key
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prom-data:/prometheus

  ldap-admin:
    image: osixia/phpldapadmin:0.7.1
    volumes:
      - ldap-data:/data
    ports:
      - "6443:443"
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap

volumes:
  tuleap-data:
  ldap-data:
  gerrit-data:
  db-data:
  db57-data:
  redis-data:
  realtime-conf:
  realtime-cert:
  reverse-proxy-cert:
  prom-data:
  jenkins-data:
